name: Clang-Tidy to Slack

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install clang-tidy
        run: |
          sudo apt update
          sudo apt install clang-tidy -y

      - name: Run clang-tidy and save output
        run: |
          clang-tidy main.cpp -- -std=c++17 > clang-tidy-report.txt 2>&1 || true

      - name: Send clang-tidy result to Slack
        run: |
          SUMMARY=$(head -n 10 clang-tidy-report.txt | sed 's/"/\\"/g' | tr '\n' '\\n')
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"🚨 *Clang-Tidy Issues Found:*\n\`\`\`${SUMMARY}\`\`\`\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
